# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39c9913d48f22194296a3e1d7e7f82e7329e984f2e9eca8059bb8b61771fd81cc034754061552b2ddab45925dfa0772df5f4d4e86baa021bde651d055dcf78fd

test:
  secret_key_base: 7cfe817dc4b2bee43dc85312744b04688bf4c427f482250cf09952c639a0d617203598bb59ba5d285a70864a7a46b5fa062a90641d99a9a8a46307306487f9c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
